# Generated by Django 4.0.3 on 2022-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='position',
        ),
        migrations.AddField(
            model_name='expenses',
            name='transaction',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
